openapi: 3.0.1
info:
  title: AccountInfoBackendAPI
  description: API Definition of AccountInfoBackendAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/accountinfo
paths:
  /:
    post:
      responses:
        default:
          description: Default response
